// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/reload-tracker': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/reload-tracker.get').default>>>>
    }
    '/api/blog/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blog/[slug].get').default>>>>
    }
    '/api/blog/cool-tags': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blog/cool-tags.get').default>>>>
    }
    '/api/blog/cron/run': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blog/cron/run.get').default>>>>
    }
    '/api/blog': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blog/index.get').default>>>>
    }
    '/api/blog/latest': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blog/latest.get').default>>>>
    }
    '/api/blog/popular': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blog/popular.get').default>>>>
    }
    '/api/blog/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blog/search.get').default>>>>
    }
    '/api/blog/suggest': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blog/suggest.get').default>>>>
    }
    '/api/generated-blogs-regenerate': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/generated-blogs-regenerate.get').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/health/auto-blog': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health/auto-blog.get').default>>>>
    }
    '/api/i18n/messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/i18n/messages.get').default>>>>
    }
    '/api/icon': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/icon.get').default>>>>
    }
    '/api/invalidate-blog-cache': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/invalidate-blog-cache.post').default>>>>
    }
    '/api/keyword-run': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/keyword-run.get').default>>>>
    }
    '/api/sitemap-dynamic': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sitemap-dynamic').default>>>>
    }
    '/api/smart-reload-tracker': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/smart-reload-tracker.post').default>>>>
    }
    '/api/test': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/test.get').default>>>>
    }
    '/api/testimonials': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/testimonials.get').default>>>>
    }
    '/api/version': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/version.get').default>>>>
    }
    '/api/visitors': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/visitors.get').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/visitors').default>>>>
    }
    '/images/blog/:name': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/images/blog/[name].get').default>>>>
    }
    '/sitemap-dynamic.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/sitemap-dynamic.xml').default>>>>
    }
    '/sitemap': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/sitemap.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__site-config__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-site-config/dist/runtime/server/routes/__site-config__/debug').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}