export const seoKeywords = [
  'jasa paypal',
  'jasa paypal terpercaya',
  'jasa paypal indonesia',
  'jasa paypal terpercaya indonesia',
  'jasa bayar paypal',
  'jasa bayar paypal terpercaya',
  'jasa bayar paypal indonesia',
  'jasa pembayaran paypal',
  'jasa pembayaran paypal terpercaya',
  'jasa kirim paypal',
  'jasa kirim paypal terpercaya',
  'jasa transfer paypal',
  'jasa transfer paypal terpercaya',
  'jasa top up paypal',
  'jasa top up paypal terpercaya',
  'jasa isi saldo paypal',
  'jasa isi saldo paypal terpercaya',
  'jasa deposit paypal',
  'jasa deposit paypal terpercaya',
  'jasa perantara paypal',
  'jasa perantara paypal terpercaya',
  'jasa bayar via paypal',
  'jasa pembayaran via paypal',
  'jasa topup saldo paypal',
  'jasa paypal murah',
  'jasa paypal murah terpercaya',
  'jasa paypal cepat',
  'jasa paypal cepat terpercaya',
  'jasa paypal aman',
  'jasa paypal aman terpercaya',
  'jasa paypal 24 jam',
  'jasa paypal 24 jam terpercaya',
  'layanan paypal indonesia',
  'layanan paypal terpercaya',
  'pembayaran paypal indonesia',
  'transfer paypal indonesia',
  'top up paypal indonesia',
  'isi saldo paypal indonesia',
  'jasa pembayaran online',
  'jasa transfer trc20',
  'jasa transfer btc',
  'jasa bayar btc',
  'jasa bayar trc20',
  'jasa bayar skrill',
  'jasa transfer skrill',
  'jasa transfer bitcoin',
  'jasa kirim bitcoin',
  'jasa bayar namecheap',
  'jasa isi saldo namecheap',
  'jasa topup saldo namecheap',
  'jasa pembayaran ahrefs',
  'jasa ahrefs',
  'jasa bayar ahrefs',
  'jasa pembayaran luar negeri'
] as const;
