// Dummy Images Index
// Generated on 2025-09-30T03:04:08.473Z

export const DUMMY_IMAGES = [
  '/images/dummy/dummy-1.jpg',
  '/images/dummy/dummy-2.jpg',
  '/images/dummy/dummy-3.jpg',
  '/images/dummy/dummy-4.jpg',
  '/images/dummy/dummy-5.jpg',
  '/images/dummy/dummy-6.jpg',
  '/images/dummy/dummy-7.jpg',
  '/images/dummy/dummy-8.jpg',
  '/images/dummy/dummy-9.jpg',
  '/images/dummy/dummy-10.jpg',
  '/images/dummy/dummy-11.jpg',
  '/images/dummy/dummy-12.jpg',
  '/images/dummy/dummy-13.jpg',
  '/images/dummy/dummy-14.jpg',
  '/images/dummy/dummy-15.jpg',
  '/images/dummy/dummy-16.jpg',
  '/images/dummy/dummy-17.jpg',
  '/images/dummy/dummy-18.jpg',
  '/images/dummy/dummy-19.jpg',
  '/images/dummy/dummy-20.jpg',
  '/images/dummy/dummy-21.jpg',
  '/images/dummy/dummy-22.jpg',
  '/images/dummy/dummy-23.jpg',
  '/images/dummy/dummy-24.jpg',
  '/images/dummy/dummy-25.jpg',
  '/images/dummy/dummy-26.jpg',
  '/images/dummy/dummy-27.jpg',
  '/images/dummy/dummy-28.jpg',
  '/images/dummy/dummy-29.jpg',
  '/images/dummy/dummy-30.jpg',
  '/images/dummy/dummy-31.jpg',
  '/images/dummy/dummy-32.jpg',
  '/images/dummy/dummy-33.jpg',
  '/images/dummy/dummy-34.jpg',
  '/images/dummy/dummy-35.jpg',
  '/images/dummy/dummy-36.jpg',
  '/images/dummy/dummy-37.jpg',
  '/images/dummy/dummy-38.jpg',
  '/images/dummy/dummy-39.jpg',
  '/images/dummy/dummy-40.jpg',
  '/images/dummy/dummy-41.jpg',
  '/images/dummy/dummy-42.jpg',
  '/images/dummy/dummy-43.jpg',
  '/images/dummy/dummy-44.jpg',
  '/images/dummy/dummy-45.jpg',
  '/images/dummy/dummy-46.jpg',
  '/images/dummy/dummy-47.jpg',
  '/images/dummy/dummy-48.jpg',
  '/images/dummy/dummy-49.jpg',
  '/images/dummy/dummy-50.jpg',
  '/images/dummy/dummy-51.jpg',
  '/images/dummy/dummy-52.jpg',
  '/images/dummy/dummy-53.jpg',
  '/images/dummy/dummy-54.jpg',
  '/images/dummy/dummy-55.jpg',
  '/images/dummy/dummy-56.jpg',
  '/images/dummy/dummy-57.jpg',
  '/images/dummy/dummy-58.jpg',
  '/images/dummy/dummy-59.jpg',
  '/images/dummy/dummy-60.jpg',
  '/images/dummy/dummy-61.jpg',
  '/images/dummy/dummy-62.jpg',
  '/images/dummy/dummy-63.jpg',
  '/images/dummy/dummy-64.jpg',
  '/images/dummy/dummy-65.jpg',
  '/images/dummy/dummy-66.jpg',
  '/images/dummy/dummy-67.jpg',
  '/images/dummy/dummy-68.jpg',
  '/images/dummy/dummy-69.jpg',
  '/images/dummy/dummy-70.jpg',
  '/images/dummy/dummy-71.jpg',
  '/images/dummy/dummy-72.jpg',
  '/images/dummy/dummy-73.jpg',
  '/images/dummy/dummy-74.jpg',
  '/images/dummy/dummy-75.jpg',
  '/images/dummy/dummy-76.jpg',
  '/images/dummy/dummy-77.jpg',
  '/images/dummy/dummy-78.jpg',
  '/images/dummy/dummy-79.jpg',
  '/images/dummy/dummy-80.jpg',
  '/images/dummy/dummy-81.jpg',
  '/images/dummy/dummy-82.jpg',
  '/images/dummy/dummy-83.jpg',
  '/images/dummy/dummy-84.jpg',
  '/images/dummy/dummy-85.jpg',
  '/images/dummy/dummy-86.jpg',
  '/images/dummy/dummy-87.jpg',
  '/images/dummy/dummy-88.jpg',
  '/images/dummy/dummy-89.jpg',
  '/images/dummy/dummy-90.jpg',
  '/images/dummy/dummy-91.jpg',
  '/images/dummy/dummy-92.jpg',
  '/images/dummy/dummy-93.jpg',
  '/images/dummy/dummy-94.jpg',
  '/images/dummy/dummy-95.jpg',
  '/images/dummy/dummy-96.jpg',
  '/images/dummy/dummy-97.jpg',
  '/images/dummy/dummy-98.jpg',
  '/images/dummy/dummy-99.jpg',
  '/images/dummy/dummy-100.jpg'
];

export function getRandomDummyImage() {
  const randomIndex = Math.floor(Math.random() * DUMMY_IMAGES.length);
  return DUMMY_IMAGES[randomIndex];
}

export function getDummyImage(index) {
  if (index >= 0 && index < DUMMY_IMAGES.length) {
    return DUMMY_IMAGES[index];
  }
  return getRandomDummyImage();
}
