// server/utils/email.ts
import { createTransport } from 'nodemailer'
import { compile } from 'handlebars'

const transporter = createTransport({
  host: process.env.SMTP_HOST,
  port: Number(process.env.SMTP_PORT),
  secure: true,
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS
  }
})

interface EmailTemplate {
  subject: string
  html: string
}

const templates = {
  moderationRequired: compile(`
    <h2>Content Moderation Required</h2>
    <p>New content requires review for post: {{title}}</p>
    <p>Generated by: {{source}}</p>
    <a href="{{reviewUrl}}">Review Content</a>
  `),

  contentApproved: compile(`
    <h2>Content Approved</h2>
    <p>The content for "{{title}}" has been approved and published.</p>
    <a href="{{postUrl}}">View Post</a>
  `),

  moderationFailed: compile(`
    <h2>Content Moderation Failed</h2>
    <p>The content for "{{title}}" failed moderation checks:</p>
    <ul>
      {{#each issues}}
        <li>{{this}}</li>
      {{/each}}
    </ul>
  `)
}

export async function sendEmail(
  to: string,
  template: keyof typeof templates,
  data: Record<string, any>
) {
  const html = templates[template](data)

  await transporter.sendMail({
    from: process.env.EMAIL_FROM,
    to,
    subject: `[Blog] ${data.title}`,
    html
  })
}
